.

diff --git a/modules/arc/Makefile b/modules/arc/Makefile
--- a/modules/arc/Makefile
+++ b/modules/arc/Makefile
@@ -10,18 +10,20 @@ ifneq ($(strip $(MAXRUNNERS)),)
   ADDITIONAL_VALUES := $(ADDITIONAL_VALUES) maxRunners=$(MAXRUNNERS)
 endif
 
+DOCKERREGISTRYBUCKET := $(shell jq '.["$(EKS_CLUSTER_NAME)"]["docker_registry_bucket"]' <"${CLUSTER_CONFIG_FILE}")
+DOCKERREGISTRYUSERSECRET := $(shell jq '.["$(EKS_CLUSTER_NAME)"]["internal_registry_secret_arn"]' <"${CLUSTER_CONFIG_FILE}")
 KARPENTERCONTROLERROLEARN := $(shell jq '.["$(EKS_CLUSTER_NAME)"]["karpenter_controler_role_arn"]' <"${CLUSTER_CONFIG_FILE}")
-KARPENTERNODEROLEARN := $(shell jq '.["$(EKS_CLUSTER_NAME)"]["karpenter_node_role_arn"]' <"${CLUSTER_CONFIG_FILE}")
 KARPENTERNODEROLE := $(shell jq '.["$(EKS_CLUSTER_NAME)"]["karpenter_node_role_name"]' <"${CLUSTER_CONFIG_FILE}")
+KARPENTERNODEROLEARN := $(shell jq '.["$(EKS_CLUSTER_NAME)"]["karpenter_node_role_arn"]' <"${CLUSTER_CONFIG_FILE}")
 KARPENTERSGIDS := $(shell jq -c '[.["$(EKS_CLUSTER_NAME)"]["security_group_ids"][] | {"id": .}]' <"${CLUSTER_CONFIG_FILE}")
 KARPENTERSUBNETIDS := $(shell jq -c '[.["$(EKS_CLUSTER_NAME)"]["subnet_ids"][] | {"id": .}]' <"${CLUSTER_CONFIG_FILE}")
-DOCKERREGISTRYBUCKET := $(shell jq '.["$(EKS_CLUSTER_NAME)"]["docker_registry_bucket"]' <"${CLUSTER_CONFIG_FILE}")
-
 
 RUNNERS_NAMESPACE = actions-runners
 RUNNERS_SYSTEM_NAMESPACE = actions-runner-system
 KARPENTER_NAMESPACE = karpenter
 DOCKER_REGISTRY_NAMESPACE = docker-registry
+DOCKER_REGISTRY_INTERNAL_NAME = pytorch-internal
+DOCKER_REGISTRY_TLS_SECRET_NAME = $(DOCKER_REGISTRY_INTERNAL_NAME)-tls
 
 .PHONY: clean-k8s-rds-state
 clean-k8s-rds-state:
@@ -77,54 +79,66 @@ create-gha-arc-secret: create-runner-namespace
 
 .PHONY: create-docker-registry-tls-secret
 create-docker-registry-tls-secret:
-	openssl req -new -newkey rsa:4096 -x509 -sha256 -days 365 -nodes -out tls/tls.crt -keyout tls/tls.key -subj "/C=US/ST=California/L=San Francisco/O=PyTorch/OU=PyTorch/CN=docker-registry-pytorch-internal"
-	kubectl create secret tls docker-registry-pytorch-internal-tls \
-		--namespace=$(DOCKER_REGISTRY_NAMESPACE) \
-		--cert=tls/tls.crt \
-		--key=tls/tls.key \
-		--dry-run=client -o yaml | kubectl apply -f -
+	echo "Checking if secret $(DOCKER_REGISTRY_TLS_SECRET_NAME) exists, if not creating it"
+	if kubectl get secret --namespace=$(DOCKER_REGISTRY_NAMESPACE) $(DOCKER_REGISTRY_TLS_SECRET_NAME) ; then \
+		echo "Secret $(DOCKER_REGISTRY_TLS_SECRET_NAME) found, not changing it" ; \
+	else \
+		echo "Secret $(DOCKER_REGISTRY_TLS_SECRET_NAME) not found, creating it" ; \
+		openssl req \
+			-new -newkey rsa:4096 -x509 -sha256 \
+			-days 3650 -nodes \
+			-out tls/tls.crt \
+			-keyout tls/tls.key \
+			-addext "subjectAltName = DNS:$(DOCKER_REGISTRY_INTERNAL_NAME).$(DOCKER_REGISTRY_NAMESPACE).svc.cluster.local" \
+			-subj "/CN=$(DOCKER_REGISTRY_INTERNAL_NAME).$(DOCKER_REGISTRY_NAMESPACE).svc.cluster.local" ; \
+		kubectl create secret tls $(DOCKER_REGISTRY_TLS_SECRET_NAME) \
+			--namespace=$(DOCKER_REGISTRY_NAMESPACE) \
+			--cert=tls/tls.crt \
+			--key=tls/tls.key \
+			--dry-run=client -o yaml | kubectl apply -f - ; \
+	fi
 
 .PHONY: install-docker-registry
-install-docker-registry: helm-repo-update create-docker-registry-tls-secret
+install-docker-registry: #helm-repo-update create-docker-registry-tls-secret
+	[ "$(REGION)" != "" ] || (echo "REGION not set"; exit 1)
 	[ "$(CLUSTER_CONFIG_FILE)" != "" ] || (echo "CLUSTER_CONFIG_FILE not set"; exit 1)
 	[ "$(EKS_CLUSTER_NAME)" != "" ] || (echo "EKS_CLUSTER_NAME not set"; exit 1)
 	[ "$$DOCKER_REGISTRY_HTPASSWD" != "" ] || (echo "DOCKER_REGISTRY_HTPASSWD not set"; exit 1)
-	helm upgrade --install docker-registry-mirror-docker-io docker-registry-mirror/docker-registry-mirror \
-		--namespace=$(DOCKER_REGISTRY_NAMESPACE) \
-		--create-namespace \
-		--wait \
-		--set service.type=ClusterIP \
-		--set service.port=5000 \
-		--set service.clusterIP=172.20.56.113 \
-		--set replicaCount=3 \
-		--set tolerations[0].key=$(ARC_SYS_TAINT),tolerations[0].operator="Exists",tolerations[0].effect=NoSchedule
-	helm upgrade --install docker-registry-mirror-ghcr-io docker-registry-mirror/docker-registry-mirror \
-		--namespace=$(DOCKER_REGISTRY_NAMESPACE) \
-		--create-namespace \
-		--wait \
-		--set proxy.remoteurl=https://ghcr.io \
-		--set proxy.username=pytorch \
-		--set proxy.password=`../../venv/bin/python ../../scripts/gh_app_get_github_token.py -i $(GHA_ID) -l $(GHA_INST_ID) -k "$$$(GHA_PRIVATE_KEY_VAR)"` \
-		--set service.type=ClusterIP \
-		--set service.port=5000 \
-		--set service.clusterIP=172.20.56.114 \
-		--set replicaCount=3 \
-		--set tolerations[0].key=$(ARC_SYS_TAINT),tolerations[0].operator="Exists",tolerations[0].effect=NoSchedule
-	helm upgrade --install docker-registry-pytorch-internal twuni/docker-registry \
-		--namespace=$(DOCKER_REGISTRY_NAMESPACE) \
-		--create-namespace \
-		--wait \
-		--set service.type=ClusterIP \
-		--set service.port=443 \
-		--set service.clusterIP=172.20.56.115 \
-		--set tlsSecretName=docker-registry-pytorch-internal-tls \
-		--set s3.bucket=$(DOCKERREGISTRYBUCKET) \
-		--set secrets.s3.accessKey=`jq '.["$(EKS_CLUSTER_NAME)"]["docker_registry_user_access_key"]' <"${CLUSTER_CONFIG_FILE}"` \
-		--set secrets.s3.secretKey=`jq '.["$(EKS_CLUSTER_NAME)"]["docker_registry_user_secret"]' <"${CLUSTER_CONFIG_FILE}"` \
-		--set replicaCount=2 \
-		--set garbageCollect.enabled=true \
-		--set secrets.htpasswd="$$DOCKER_REGISTRY_HTPASSWD" \
-		--set tolerations[0].key=$(ARC_SYS_TAINT),tolerations[0].operator="Exists",tolerations[0].effect=NoSchedule
+	# helm upgrade --install docker-registry-mirror-docker-io docker-registry-mirror/docker-registry-mirror \
+	# 	--namespace=$(DOCKER_REGISTRY_NAMESPACE) \
+	# 	--create-namespace \
+	# 	--wait \
+	# 	--set service.type=ClusterIP \
+	# 	--set service.port=5000 \
+	# 	--set service.clusterIP=172.20.56.113 \
+	# 	--set replicaCount=3 \
+	# 	--set tolerations[0].key=$(ARC_SYS_TAINT),tolerations[0].operator="Exists",tolerations[0].effect=NoSchedule
+	# helm upgrade --install docker-registry-mirror-ghcr-io docker-registry-mirror/docker-registry-mirror \
+	# 	--namespace=$(DOCKER_REGISTRY_NAMESPACE) \
+	# 	--create-namespace \
+	# 	--wait \
+	# 	--set proxy.remoteurl=https://ghcr.io \
+	# 	--set proxy.username=pytorch \
+	# 	--set proxy.password=`../../venv/bin/python ../../scripts/gh_app_get_github_token.py -i $(GHA_ID) -l $(GHA_INST_ID) -k "$$$(GHA_PRIVATE_KEY_VAR)"` \
+	# 	--set service.type=ClusterIP \
+	# 	--set service.port=5000 \
+	# 	--set service.clusterIP=172.20.56.114 \
+	# 	--set replicaCount=3 \
+	# 	--set tolerations[0].key=$(ARC_SYS_TAINT),tolerations[0].operator="Exists",tolerations[0].effect=NoSchedule
+	# helm upgrade --install $(DOCKER_REGISTRY_INTERNAL_NAME) twuni/docker-registry \
+	# 	--namespace=$(DOCKER_REGISTRY_NAMESPACE) \
+	# 	--create-namespace \
+	# 	--wait \
+	# 	--set tlsSecretName=$(DOCKER_REGISTRY_TLS_SECRET_NAME) \
+	# 	--set s3.region=$(REGION) \
+	# 	--set s3.bucket=$(DOCKERREGISTRYBUCKET) \
+	# 	--set secrets.s3.accessKey=`jq '.["$(EKS_CLUSTER_NAME)"]["docker_registry_user_access_key"]' <"${CLUSTER_CONFIG_FILE}"` \
+	# 	--set secrets.s3.secretKey=`jq '.["$(EKS_CLUSTER_NAME)"]["docker_registry_user_secret"]' <"${CLUSTER_CONFIG_FILE}"` \
+	# 	--set secrets.htpasswd="$$DOCKER_REGISTRY_HTPASSWD" \
+	# 	--set tolerations[0].key=$(ARC_SYS_TAINT),tolerations[0].operator="Exists",tolerations[0].effect=NoSchedule \
+	# 	--set fullnameOverride=$(DOCKER_REGISTRY_INTERNAL_NAME) \
+	# 	--values k8s/internal-docker-registry.yaml
+	kubectl patch svc $(DOCKER_REGISTRY_INTERNAL_NAME) --namespace=$(DOCKER_REGISTRY_NAMESPACE) --patch-file k8s/pytorch-internal-svc-patch.yaml
 
 .PHONY: install-arc
 install-arc: helm-repo-update create-gha-arc-secret
@@ -191,7 +205,8 @@ setup-karpenter-autoscaler: install-karpenter install-docker-registry
 			projecttag=$(PROJECTTAG) \
 			dockerregistrymirror=`kubectl get svc --namespace=docker-registry docker-registry-mirror-docker-io -o json | jq ".spec.clusterIP" | sed 's/"//g'` \
 			githubregistrymirror=`kubectl get svc --namespace=docker-registry docker-registry-mirror-ghcr-io -o json | jq ".spec.clusterIP" | sed 's/"//g'` \
-			pytorchregistrymirror=`kubectl get svc --namespace=docker-registry docker-registry-pytorch-internal -o json | jq ".spec.clusterIP" | sed 's/"//g'` \
+			pytorchregistrymirror=`kubectl get svc --namespace=docker-registry $(DOCKER_REGISTRY_INTERNAL_NAME) -o json | jq ".spec.clusterIP" | sed 's/"//g'` \
+			DOCKERREGISTRYUSERSECRET=$(DOCKERREGISTRYUSERSECRET) \
 		--root-classes nodeConfig \
 		--label-property nodeType
 	../../venv/bin/python3 ../../scripts/kubectl_apply_runner_templates.py \
@@ -208,6 +223,7 @@ setup-karpenter-autoscaler: install-karpenter install-docker-registry
 			karpentersubnetids='$(KARPENTERSUBNETIDS)' \
 			project=gh-ci-$(EKS_ENVIRONMENT)-arc \
 			projecttag=$(PROJECTTAG) \
+			DOCKERREGISTRYUSERSECRET=$(DOCKERREGISTRYUSERSECRET) \
 		--root-classes nodeConfig \
 		--label-property nodeType
 
